export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SEMANTIC_VALIDATION_ERROR: 'SEMANTIC_VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  RESPONSE_VALIDATION_ERROR: 'RESPONSE_VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
